[theme]
primaryColor="#1a56db"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans-serif"


# esto es solo local dejenlo, no afecta a heroku

#estoy intentando algo

# [server]
# unOnSave = false
